server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/microservice_shop}
spring.datasource.username=${DB_USER:microservice_shop}
spring.datasource.password=${DB_PASSWORD:microservice_shop}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

spring.rabbitmq.uri=${RABBIT_URL:amqp://guest:guest@localhost:5672}
